import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@/components/Nav'
import Providers from './providers'
import SessionProvider from './sessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="system">
            <main className="min-h-screen container py-6">
              <Nav />

              {children}
            </main>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  )
}
